var GAME_LEVELS = [
  ["                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                             xxxxxx                                              ",
   "  xxxxxxxxx                                                                      ",
   "  xxxxxxx                 xxxxxx                                                 ",
   "  xxxx          xxxxxxxxx               xxxxx          xxxxxxxxxxxxx o o o o  y  ",
   "  xxx   @        xxxxxxxxxx                                 xxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx      xx                   ",
   "                              x   x                  x     xx                    ",
   "                              x!!!x                  x!!!!!x                     ",
   "                              x!!!x                  x!!!!!x                     ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 "],
  ["                                                                                                                ",
   "                                                                                                                ",
   "                                                                                               xxxxx            ",
   "                                                                                             xxxxxxxx           ",
   "                                                                                          xxxxxxxxxxxx          ",
   "                                                                                                  xxxxx         ",
   "                                                                                                   xxx          ",
   "                                                                                         xxxx   xxxxx           ",
   "                                                                                   xxx   ooo     xxxx           ",
   "                                                                                xxx      oooo   xxxx            ",
   "                                                                            xxx           xxx   xxx             ",
   "                                                                        xxx                 x   x               ",
   "                                                                    xxx                     x   x               ",
   "                                                                 xxx                        x   x               ",
   "                     o                                       xxx                o o         x   xxx             ",
   "                   xxxx                                                      xxxxxxxxx      x    xxx            ",
   "                xxxx                       o  o            xxx                          o  xx     xxx           ",
   "            xxxxx                         xxxxxxx                                      xxxxx  yyy  xxxxx        ",
   "   @     xxxxx                                                                       xxxxxxxxxxxxxxxxxxxxxxx    ",
   "  xxxxxxxx             xxxxxxxxxxxxxxxxxx         xxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "        xx   o o o o                                                              o o o o o o o o o o o o o o x ",
   "        xxxxxxxxxxxxxxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "!!!!!!!!!!!!!!!!!!!!!!!                                                                                         ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                 "],
  [" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                        xxxxxxxxxxxxxxxxxxxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                        xxxxxxxx            xxxxxxx                                           ",
   "                                      xxxxxxxxx           xxxxxxxxxxx                                         ",
   "                                xxxxxxxxxx                      xxxxxxxxx                                     ",
   "                                    xxxxxxx     sun           xxxxxxxxx                                       ",
   "                                        xxx                 xxxxxx                                            ",
   "                                          xxxxxxxxxxxxxxxxxxxx xxx                                            ",
   "                                           xxx   xxxx  xxxx  xxxxxx                                           ",
   "                                           xx      xxxx  xxx    xxxx                                          ",
   "                                           x        xxx     xx    xxx                                         ",
   "                                                    x       x       x                                         ",
   "                                                                                                              ", 
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "         xx                                                                                                   ",
   "  x     xxxx     x                                                                                            ",
   "  xxx xx   xx  xxxx                                                                                           ",
   "   xxxx      xxxx                                                                                             ",
   "     x        x                                                                                               ",
   "     x        x                                                                                               ",
   "     x        x                                                                                               ",
   "     x   y                                                                                                    ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                           ",
   " x!!!!!!!!!xxxxxxxx        !!!!!!!xxxxx                                                                       ",
   " x!!!!!!  xxxxxxxxx               !!!!xxxxxxx                                                                 ",
   " x!!!!    xxxxxxxx                        xxxxxxxxx                                                           ",
   " x         xxxxxx                             xxxxxxxxxxx                                                     ",
   " x          xx                                               xxxxxxxxxx                                       ",
   " x                                       o                     xxxxx  xxxxxxxxxxxxx                           ",
   " x                  x                   xxxxxxx                 xxx    xxxxx  xxxxxxxxxxxx                    ",
   " x                  xx                   xxxxxx                         xxxx       !!!!xxxxxxxxxxxx           ",
   " x                  xxxxxxxx    xxx    xxxx                           x            !!!!                       ",
   "                                       xx                                                                     ",
   "                                       x                                                               xxxxxx ",
   "                          xxxxxxxx                                                                    xxxxxxx ",
   " @                  xxxx                                                                              xxxxxxx ",
   " xxxxxxx                 x     x                        xxxx                                          xxxxxxx ",
   "  oooo xxxxxx           xx    xxx                                 xxxxxxxxxx                        xxxxxxxxx ",
   "  oooo    xxxxx     xxxxxx!!!!xxxx                                        xxxx                 xxxxxxxxxx     ",
   "  oooo                xxxx!!!!xxxxx    o o o       o o                      xxxxx          xxxxxxxxxxxxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                  xxxxxxxxxxxx                                                                  ",
   "                              xxxxxxxxxx    xxxxxxxxx                                                           ",
   "                    xxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxx                                               ",
   "                xxxxxx                                 xxxxxx                                                   ",
   "           xxxxxxxxxx      o o                o o o    xxxxxxx                                                  ",
   "          xxxxxxxxxxxxxxx                                                                      xx               ",
   "            x       xxxxxxx                          xxxxxxxx                                 xxxx              ",
   "            x         xxxxxxxxxxx              xxxxxxxxxxxxx                                   xx               ",
   "            x         xxxxxxxxxx              xxxxxxxxxxx  x                                  xxxx              ",
   "            x                       xxxxxxxxxxxxxx         x                                   xx               ",
   "            xxxxx                                          x                                  xxxx              ",
   "                      xxx                                  xxxxxxxxxx                       xxxxxxx             ",
   "                       xxx                                 x                      x        xxxxxxxxx        x   ",
   "        x      x        xxx                           xxxxxx                     xx       xx       xx       xx  ",
   "  x    x x   xxx        xxxx o            xxx                                   xxx    xxx          xxx    xxx  ",
   "   xx xx   xxxxx    xxxxxxxx          xx                                          xxxxxxxx           xxxxxxxx   ",
   "   xxxx   xx        xxx                 xx                                           xxxx            xxxx       ",
   "   xx               xxx         xxxxxxxxxxx                                           x                x        ",
   "   x             xxxx                 xxxx                                            x                x        ",
   "   x         xxxxx                   xxxx                                             x                x        ",
   "   x  @   xxxxxx            o        xxxxxx                                           x                x        ",
   "  xxxxxxxxxxxx              xxxx    xxx xxxxxxx                                       x                x        ",
   "                       xxxxxxxxx    xxxx                  xxxxxx                                       x        ",
   "                            xxxx    xxxxx           xxxxxxxx              xxxxxx                  xxxxxxxx      ",
   "             xxx          xxxxx       xxxx          o o xxxxxx            xxxxxxxx                   xxxxxxx    ",
   "            xxxx         xxxxxx        xxxxxx       xxxxxx                      xxxxxxx                   xxxxx ",
   "  o o o    xxx  ooo   xxxxxx o o o o o o o  xxxxxxxx    xxxxxx   o o                xxxxxxxx            y   xxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                     x!!!!!! x                                  ",
   "                                                                     x!!!!!! x                                  ",
   "                                                                     xxxxxxxxx                                  "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
